# Python 3.9をベースにする
FROM python:3.9-slim

# 環境変数を設定
ENV APP_HOME /app
WORKDIR $APP_HOME

# 必要なライブラリをインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションのコードをコピー
COPY . .

# サーバーを起動するコマンド
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app